//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Chaosmonkey) DeepCopyInto(out *Chaosmonkey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Chaosmonkey.
func (in *Chaosmonkey) DeepCopy() *Chaosmonkey {
	if in == nil {
		return nil
	}
	out := new(Chaosmonkey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Chaosmonkey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmonkeyList) DeepCopyInto(out *ChaosmonkeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Chaosmonkey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmonkeyList.
func (in *ChaosmonkeyList) DeepCopy() *ChaosmonkeyList {
	if in == nil {
		return nil
	}
	out := new(ChaosmonkeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChaosmonkeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmonkeySpec) DeepCopyInto(out *ChaosmonkeySpec) {
	*out = *in
	out.Period = in.Period
	if in.WithLabels != nil {
		in, out := &in.WithLabels, &out.WithLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WithFields != nil {
		in, out := &in.WithFields, &out.WithFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmonkeySpec.
func (in *ChaosmonkeySpec) DeepCopy() *ChaosmonkeySpec {
	if in == nil {
		return nil
	}
	out := new(ChaosmonkeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosmonkeyStatus) DeepCopyInto(out *ChaosmonkeyStatus) {
	*out = *in
	in.LastDelete.DeepCopyInto(&out.LastDelete)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosmonkeyStatus.
func (in *ChaosmonkeyStatus) DeepCopy() *ChaosmonkeyStatus {
	if in == nil {
		return nil
	}
	out := new(ChaosmonkeyStatus)
	in.DeepCopyInto(out)
	return out
}
