# permissions for end users to view chaosmonkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaosmonkey-viewer-role
rules:
- apiGroups:
  - onboarding.my.domain
  resources:
  - chaosmonkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - onboarding.my.domain
  resources:
  - chaosmonkeys/status
  verbs:
  - get
